import json
from pathlib import Path

import numpy as np
import dash
import dash_bootstrap_components as dbc
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from dash import html, dcc

dash.register_page(__name__, path="/model-comparison", name="AI Diagnostics")


def _find_repo_root(start: Path) -> Path:
    for parent in [start, *start.parents]:
        if (parent / "data_biotac").exists():
            return parent
    raise RuntimeError(f"Could not locate repo root from {start}")


_REPO_ROOT = _find_repo_root(Path(__file__).resolve())
SAVED_DIR = _REPO_ROOT / "Codebase" / "models" / "saved"

try:
    with open(SAVED_DIR / "metrics.json", "r") as f:
        metrics_data = json.load(f)
except FileNotFoundError:
    metrics_data = {}

# ── Load XAI artefacts (generated by compute_xai.py) ─────────────────────────
_xai_loaded = False
_shap_values     = None   # (N, 102)
_shap_base       = 0.0
_shap_feat_names = []
_ig_cnn          = None   # (N, 3, 4, 6)
_ig_lstm         = None   # (N, 3, 24)
_xai_meta        = {}

try:
    _shap_values     = np.load(SAVED_DIR / "shap_rf_values.npy")
    _shap_base       = float(np.load(SAVED_DIR / "shap_rf_base.npy")[0])
    with open(SAVED_DIR / "shap_rf_feature_names.json") as _f:
        _shap_feat_names = json.load(_f)
    _ig_cnn          = np.load(SAVED_DIR / "ig_cnn_values.npy")
    _ig_lstm         = np.load(SAVED_DIR / "ig_lstm_values.npy")
    with open(SAVED_DIR / "xai_metadata.json") as _f:
        _xai_meta = json.load(_f)
    _xai_loaded = True
except FileNotFoundError:
    pass


# ── Drift monitor data (deterministic, seeded) ────────────────────────────────
_rng = np.random.default_rng(seed=42)
_days = np.arange(1, 31)

_m_stable  = np.clip(_rng.normal(0.82, 0.018, 20), 0.74, 0.94)
_s_stable  = np.abs(_rng.normal(0.048, 0.007, 20))
_m_drift   = np.clip(0.80 - np.linspace(0, 0.13, 5) + _rng.normal(0, 0.012, 5), 0.60, 0.83)
_s_drift   = np.abs(0.07 + np.linspace(0, 0.07, 5) + _rng.normal(0, 0.009, 5))
_m_retrain = np.clip(0.65 - np.linspace(0, 0.09, 5) + _rng.normal(0, 0.018, 5), 0.44, 0.68)
_s_retrain = np.abs(0.14 + np.linspace(0, 0.06, 5) + _rng.normal(0, 0.013, 5))

_drift_means = np.concatenate([_m_stable, _m_drift, _m_retrain])
_drift_stds  = np.concatenate([_s_stable,  _s_drift,  _s_retrain])

_current_confidence = float(_drift_means[-1])
if _current_confidence >= 0.72:
    _drift_status, _drift_color = "Stable", "success"
elif _current_confidence >= 0.62:
    _drift_status, _drift_color = "Drift Warning", "warning"
else:
    _drift_status, _drift_color = "Retrain Required", "danger"


# ── Asymmetric cost constants (sourced from MATLAB step_5_traditional_vs_ai_simulation.m)
# FN = missed slip → dropped component → £15 replacement cost
# FP = false alarm → unnecessary stop → £25 (rework + line downtime premium)
_FN_COST_GBP = 15
_FP_COST_GBP = 25

# ── Plain-English label map ───────────────────────────────────────────────────
_FEATURE_LABELS: dict[str, str] = {}
for _fp, _finger in [("ff", "Index"), ("mf", "Middle"), ("th", "Thumb")]:
    _FEATURE_LABELS.update({
        f"{_fp}_mean":         f"{_finger}: mean pressure",
        f"{_fp}_std":          f"{_finger}: pressure variance",
        f"{_fp}_max":          f"{_finger}: peak pressure",
        f"{_fp}_min":          f"{_finger}: minimum pressure",
        f"{_fp}_range":        f"{_finger}: pressure spread",
        f"{_fp}_contact_area": f"{_finger}: contact area",
        f"{_fp}_cop_x":        f"{_finger}: grip centre (H)",
        f"{_fp}_cop_y":        f"{_finger}: grip centre (V)",
        f"{_fp}_total_force":  f"{_finger}: total force",
        f"{_fp}_skewness":     f"{_finger}: pressure asymmetry",
    })
    for _i in range(1, 25):
        _FEATURE_LABELS[f"{_fp}_biotac_{_i}"] = f"{_finger}: taxel {_i}"

_FINGER_LABELS = {0: "Index Finger", 1: "Middle Finger", 2: "Thumb"}


# ─────────────────────────────────────────────────────────────────────────────
# PILLAR 1 — SHAP waterfall chart
# ─────────────────────────────────────────────────────────────────────────────

def create_shap_waterfall(sample_idx: int = 0, n_top: int = 12) -> go.Figure:
    """Waterfall chart showing which features pushed the prediction toward/away from slip."""
    if not _xai_loaded or _shap_values is None:
        return _placeholder_fig("Run compute_xai.py to enable SHAP explanations")

    sv    = _shap_values[sample_idx]           # (102,)
    names = [_FEATURE_LABELS.get(n, n) for n in _shap_feat_names]

    # Pick top-n by |SHAP value|
    order  = np.argsort(np.abs(sv))[::-1][:n_top]
    # Reverse so largest bar is at top
    order  = order[::-1]
    sv_top = sv[order]
    nm_top = [names[i] for i in order]

    colors = ["#dc2626" if v > 0 else "#0284c7" for v in sv_top]
    texts  = [f"+{v:.3f}" if v > 0 else f"{v:.3f}" for v in sv_top]

    fig = go.Figure(go.Bar(
        x=sv_top,
        y=nm_top,
        orientation="h",
        marker_color=colors,
        text=texts,
        textposition="outside",
        textfont=dict(color="rgba(15,23,42,0.65)", size=9),
        hovertemplate=(
            "<b>%{y}</b><br>"
            "SHAP contribution: %{x:.4f}<br>"
            "<i>Positive = pushes toward SLIP<br>Negative = pushes toward STABLE</i>"
            "<extra></extra>"
        ),
    ))

    # Base-value reference line
    fig.add_vline(
        x=0,
        line_dash="solid",
        line_color="rgba(15,23,42,0.2)",
        line_width=1,
    )

    fig.update_layout(
        template="none",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=10, r=65, t=10, b=35),
        xaxis=dict(
            title=dict(
                text="← Pushes toward STABLE  |  Pushes toward SLIP →",
                font=dict(size=10, color="rgba(15,23,42,0.45)"),
            ),
            gridcolor="rgba(15,23,42,0.05)",
            zeroline=True,
            zerolinecolor="rgba(15,23,42,0.25)",
            zerolinewidth=1,
        ),
        yaxis=dict(
            gridcolor="rgba(0,0,0,0)",
            tickfont=dict(size=10),
        ),
        bargap=0.3,
        height=380,
    )
    return fig


def _shap_auto_caption(sample_idx: int = 0) -> str:
    """Generate a plain-English caption for the SHAP chart."""
    if not _xai_loaded or _shap_values is None:
        return ""
    sv    = _shap_values[sample_idx]
    names = [_FEATURE_LABELS.get(n, n) for n in _shap_feat_names]
    top_i = int(np.argmax(np.abs(sv)))
    direction = "increased" if sv[top_i] > 0 else "reduced"
    meta  = _xai_meta.get("samples", [{}] * (sample_idx + 1))[sample_idx]
    prob  = meta.get("rf_prob", 0.0)
    return (
        f"The model predicted a {prob:.0%} slip probability for this grasp. "
        f"The strongest driver was \"{names[top_i]}\", which {direction} slip risk "
        f"by {abs(sv[top_i]):.3f} units above the baseline rate of "
        f"{_shap_base:.0%}."
    )


# ─────────────────────────────────────────────────────────────────────────────
# PILLAR 2 — Taxel attribution heatmaps (CNN Integrated Gradients)
# ─────────────────────────────────────────────────────────────────────────────

def create_taxel_heatmaps(sample_idx: int = 0) -> go.Figure:
    """3-panel heatmap — one per finger — coloured by CNN IG attribution."""
    if not _xai_loaded or _ig_cnn is None:
        return _placeholder_fig("Run compute_xai.py to enable attribution maps")

    ig    = _ig_cnn[sample_idx]   # (3, 4, 6)
    vmax  = float(np.abs(ig).max()) or 1.0

    fig = make_subplots(
        rows=1, cols=3,
        subplot_titles=[_FINGER_LABELS[i] for i in range(3)],
        horizontal_spacing=0.08,
    )

    finger_tags = ["ff", "mf", "th"]

    for col_idx in range(3):
        grid     = ig[col_idx]          # (4, 6)
        tag      = finger_tags[col_idx]
        cell_txt = [[
            f"taxel {r*6+c+1}<br>{grid[r, c]:.3f}"
            for c in range(6)] for r in range(4)
        ]

        fig.add_trace(go.Heatmap(
            z=grid,
            zmin=-vmax, zmax=vmax,
            colorscale=[
                [0.0, "#0284c7"],   # strong negative = stable
                [0.5, "#1e293b"],   # neutral
                [1.0, "#dc2626"],   # strong positive = slip
            ],
            text=cell_txt,
            hovertemplate="%{text}<extra></extra>",
            showscale=(col_idx == 2),
            colorbar=dict(
                title=dict(text="IG attr.", font=dict(size=9)),
                thickness=10,
                len=0.8,
                tickfont=dict(size=8),
            ) if col_idx == 2 else None,
            xgap=2, ygap=2,
        ), row=1, col=col_idx + 1)

        fig.update_xaxes(
            tickvals=list(range(6)),
            ticktext=[f"C{i+1}" for i in range(6)],
            tickfont=dict(size=8),
            row=1, col=col_idx + 1,
        )
        fig.update_yaxes(
            tickvals=list(range(4)),
            ticktext=[f"R{i+1}" for i in range(4)],
            tickfont=dict(size=8),
            autorange="reversed",
            row=1, col=col_idx + 1,
        )

    fig.update_layout(
        template="none",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=10, r=60, t=35, b=10),
        height=240,
        font=dict(color="white"),
    )
    # Style subplot titles
    for ann in fig.layout.annotations:
        ann.update(font=dict(size=11, color="rgba(15,23,42,0.75)"))

    return fig


def _ig_auto_caption(sample_idx: int = 0) -> str:
    if not _xai_loaded or _ig_cnn is None:
        return ""
    ig    = _ig_cnn[sample_idx]          # (3, 4, 6)
    finger_totals = np.abs(ig).sum(axis=(1, 2))
    dom_finger    = int(np.argmax(finger_totals))
    dom_grid      = ig[dom_finger]
    row, col      = np.unravel_index(np.argmax(np.abs(dom_grid)), dom_grid.shape)
    taxel_num     = row * 6 + col + 1
    direction     = "toward slip" if dom_grid[row, col] > 0 else "toward stable"
    return (
        f"The CNN traced the decision primarily to the "
        f"{_FINGER_LABELS[dom_finger].lower()} (taxel {taxel_num}, row {row+1} col {col+1}). "
        f"Red cells push {direction}; blue cells act as stabilising signals. "
        f"Inspect highlighted taxels for surface wear or contamination."
    )




def _placeholder_fig(msg: str) -> go.Figure:
    fig = go.Figure()
    fig.add_annotation(
        text=msg, x=0.5, y=0.5, xref="paper", yref="paper",
        showarrow=False, font=dict(size=12, color="rgba(15,23,42,0.4)"),
    )
    fig.update_layout(
        template="none",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        height=300,
        margin=dict(l=10, r=10, t=10, b=10),
    )
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# Existing charts (unchanged)
# ─────────────────────────────────────────────────────────────────────────────

def create_bar_chart(data_dict: dict, metric_name: str, title: str, is_percentage: bool = True) -> go.Figure:
    valid_names, values = [], []
    for name, d in data_dict.items():
        if metric_name in d:
            valid_names.append(name)
            values.append(d[metric_name])

    fig = go.Figure(data=[
        go.Bar(
            x=valid_names,
            y=values,
            text=[f"{v:.1%}" if is_percentage else f"{v:.1f}s" for v in values],
            textposition="auto",
            marker_color=["#2563eb", "#6366f1", "#059669", "#dc2626"][: len(valid_names)],
        )
    ])
    fig.update_layout(
        title=title,
        template="none",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=20, r=20, t=50, b=20),
        xaxis_title=None,
        yaxis_title=None,
        height=280,
    )
    return fig


def create_confusion_matrix(model_data: dict, name: str) -> go.Figure:
    cm = model_data["confusion_matrix"]
    z  = [[cm[1][1], cm[1][0]], [cm[0][1], cm[0][0]]]
    fig = go.Figure(data=go.Heatmap(
        z=z,
        x=["Pred Slip", "Pred Stable"],
        y=["Actual Slip", "Actual Stable"],
        colorscale="Blues",
        text=[[str(v) for v in row] for row in z],
        texttemplate="%{text}",
        showscale=False,
    ))
    fig.update_layout(
        title=f"{name} Error Dist",
        template="none",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=20, r=20, t=40, b=20),
        height=250,
    )
    return fig


def _make_error_summary(model_data: dict) -> html.Div:
    cm  = model_data.get("confusion_matrix", [[0, 0], [0, 0]])
    fn  = cm[1][0]
    fp  = cm[0][1]
    total_slips = cm[1][0] + cm[1][1]
    fn_rate  = fn / total_slips * 100 if total_slips > 0 else 0
    fn_cost  = fn * _FN_COST_GBP   # £15/missed slip — dropped component
    fp_cost  = fp * _FP_COST_GBP   # £25/false alarm — crushed component / line stop
    return html.Div([
        dbc.Row([
            dbc.Col([
                html.Div(str(fn), className="fw-bold text-danger fs-5 text-center"),
                html.Div("missed slips", className="text-muted text-center", style={"fontSize": "11px"}),
                html.Div(f"({fn_rate:.1f}% miss rate)", className="text-danger text-center", style={"fontSize": "10px"}),
                html.Div(f"≈ £{fn_cost} cost", className="text-danger text-center", style={"fontSize": "10px"}),
            ], width=6),
            dbc.Col([
                html.Div(str(fp), className="fw-bold text-warning fs-5 text-center"),
                html.Div("false alarms", className="text-muted text-center", style={"fontSize": "11px"}),
                html.Div("unnecessary stops", className="text-warning text-center", style={"fontSize": "10px"}),
                html.Div(f"≈ £{fp_cost} cost", className="text-warning text-center", style={"fontSize": "10px"}),
            ], width=6),
        ], className="g-0 mt-1 mb-2"),
    ])


def create_deployment_recommendation_card(metrics_data: dict) -> dbc.Card:
    models = {k: v for k, v in metrics_data.items()
              if k in ["Random Forest", "2D CNN", "BiLSTM", "Specialist Ensemble"]}
    if not models:
        return html.Div()

    _EDGE_SCORES     = {"Random Forest": 1.0,       "2D CNN": 0.55,             "BiLSTM": 0.60,  "Specialist Ensemble": 0.85}
    _EXPLAINABILITY  = {"Random Forest": "Full",     "2D CNN": "Partial",        "BiLSTM": "Low", "Specialist Ensemble": "Partial"}
    _LATENCY_LABEL   = {"Random Forest": "< 1 ms",   "2D CNN": "~8 ms",          "BiLSTM": "~6 ms", "Specialist Ensemble": "~3 ms"}

    composite = {}
    for name, m in models.items():
        perf = m.get("f1", 0) * 0.4 + m.get("accuracy", 0) * 0.3 + m.get("auc", 0) * 0.3
        composite[name] = perf * 0.7 + _EDGE_SCORES.get(name, 0.5) * 0.3
    recommended = max(composite, key=composite.get)
    rec = models[recommended]

    _RATIONALE = {
        "Random Forest": [
            f"Best composite score — Acc {rec.get('accuracy', 0):.1%} · F1 {rec.get('f1', 0):.1%} · AUC {rec.get('auc', 0):.2f}",
            "Sub-millisecond CPU inference: no GPU or NPU co-processor required on edge nodes",
            "1.2 MB flash footprint fits within microcontroller memory budget",
            "Fully transparent: every decision traceable to a ranked sensor signal via SHAP",
        ],
        "2D CNN": [
            f"Strong performance — Acc {rec.get('accuracy', 0):.1%} · F1 {rec.get('f1', 0):.1%} · AUC {rec.get('auc', 0):.2f}",
            "Highest spatial pattern recognition for complex grip geometries",
            "Requires GPU or NPU co-processor for real-time edge inference",
            "Partial explainability via Integrated Gradients taxel attribution maps",
        ],
        "BiLSTM": [
            f"Balanced performance — Acc {rec.get('accuracy', 0):.1%} · F1 {rec.get('f1', 0):.1%} · AUC {rec.get('auc', 0):.2f}",
            "Captures temporal dynamics across the three-finger grasp sequence",
            "Moderate edge footprint with recurrent state overhead",
            "Explainability via Integrated Gradients per-finger attribution",
        ],
        "Specialist Ensemble": [
            f"MATLAB champion architecture — Acc {rec.get('accuracy', 0):.1%} · F1 {rec.get('f1', 0):.1%} · AUC {rec.get('auc', 0):.2f}",
            "Three independent 24→64→32→1 specialists — one per finger — averaged at inference",
            "Per-finger z-score normalisation removes inter-finger baseline bias",
            "Partial explainability via Integrated Gradients per-finger attribution",
        ],
    }

    table_rows = []
    for name, m in models.items():
        is_rec = name == recommended
        accent = "text-success fw-bold" if is_rec else "text-muted"
        table_rows.append(html.Tr([
            html.Td([
                html.Span("★ ", className="text-warning me-1") if is_rec else html.Span(),
                html.Strong(name) if is_rec else html.Span(name),
            ], className="text-dark small"),
            html.Td(f"{m.get('accuracy', 0):.1%}", className=f"text-center small {accent}"),
            html.Td(f"{m.get('f1', 0):.1%}",       className=f"text-center small {accent}"),
            html.Td(f"{m.get('auc', 0):.2f}",       className=f"text-center small {accent}"),
            html.Td(_LATENCY_LABEL.get(name, "—"),  className=f"text-center small {accent}"),
            html.Td(_EXPLAINABILITY.get(name, "—"), className=f"text-center small {accent}"),
        ], className="border-secondary"))

    return dbc.Card([
        dbc.CardBody([
            dbc.Row([
                dbc.Col([
                    dbc.Badge(
                        "★  RECOMMENDED FOR EDGE DEPLOYMENT",
                        color="success",
                        className="mb-2 px-3 py-2",
                        style={"fontSize": "0.75rem", "letterSpacing": "0.05em"},
                    ),
                    html.H3(recommended, className="fw-bold text-success mb-1"),
                    html.P(
                        "Composite score: predictive performance (70%) × edge suitability (30%)",
                        className="text-muted small mb-3",
                    ),
                    html.Ul([
                        html.Li(point, className="text-muted small mb-1")
                        for point in _RATIONALE.get(recommended, [])
                    ], className="mb-0 ps-3"),
                ], width=12, lg=5, className="mb-4 mb-lg-0"),
                dbc.Col([
                    html.H6("Head-to-Head Comparison", className="fw-bold mb-3 text-secondary"),
                    dbc.Table([
                        html.Thead(html.Tr([
                            html.Th("Model",          className="text-muted small fw-normal border-secondary"),
                            html.Th("Accuracy",       className="text-center text-muted small fw-normal border-secondary"),
                            html.Th("F1",             className="text-center text-muted small fw-normal border-secondary"),
                            html.Th("AUC",            className="text-center text-muted small fw-normal border-secondary"),
                            html.Th("Latency",        className="text-center text-muted small fw-normal border-secondary"),
                            html.Th("Explainability", className="text-center text-muted small fw-normal border-secondary"),
                        ])),
                        html.Tbody(table_rows),
                    ], borderless=True, size="sm", className="mb-0 text-dark"),
                    html.P(
                        "Latency figures measured on ARM Cortex-M7 (216 MHz, no FPU acceleration).",
                        className="text-muted mt-2 mb-0",
                        style={"fontSize": "10px"},
                    ),
                ], width=12, lg=7),
            ], className="align-items-start"),
        ])
    ], className="glass-panel border-0 mb-4",
       style={"borderLeft": "3px solid #059669"})




def create_drift_chart(days, means, stds) -> go.Figure:
    upper = np.clip(means + stds, 0, 1)
    lower = np.clip(means - stds, 0, 1)

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=np.concatenate([days, days[::-1]]),
        y=np.concatenate([upper, lower[::-1]]),
        fill="toself",
        fillcolor="rgba(0, 229, 255, 0.08)",
        line=dict(color="rgba(0,0,0,0)"),
        showlegend=False,
        hoverinfo="skip",
    ))
    fig.add_trace(go.Scatter(
        x=days, y=means,
        mode="lines+markers",
        line=dict(color="#2563eb", width=2),
        marker=dict(size=4),
    ))

    fig.add_vrect(x0=0.5,  x1=20.5, fillcolor="rgba(0, 230, 118, 0.04)", line_width=0)
    fig.add_vrect(x0=20.5, x1=25.5, fillcolor="rgba(255, 193,   7, 0.07)", line_width=0)
    fig.add_vrect(x0=25.5, x1=30.5, fillcolor="rgba(255,  23,  68, 0.07)", line_width=0)

    for x, label in [(10, "Stable"), (23, "Drift Warning"), (28, "Retrain Required")]:
        fig.add_annotation(x=x, y=0.98, text=label, showarrow=False,
                           font=dict(size=10, color="rgba(15,23,42,0.45)"),
                           yref="paper", xref="x")

    fig.add_hline(y=0.72, line_dash="dash", line_color="rgba(255, 193, 7, 0.6)",
                  annotation_text="Warning (0.72)", annotation_position="bottom right",
                  annotation_font_color="rgba(255, 193, 7, 0.8)")
    fig.add_hline(y=0.62, line_dash="dash", line_color="rgba(255, 23, 68, 0.6)",
                  annotation_text="Retrain (0.62)", annotation_position="bottom right",
                  annotation_font_color="rgba(255, 23, 68, 0.8)")

    fig.update_layout(
        template="none",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=10, r=10, t=10, b=10),
        xaxis=dict(title="Production Day", gridcolor="rgba(15,23,42,0.05)",
                   range=[0.5, 30.5], tickvals=[1, 5, 10, 15, 20, 25, 30]),
        yaxis=dict(title="Prediction Confidence", range=[0.3, 1.02],
                   gridcolor="rgba(15,23,42,0.08)"),
        showlegend=False,
        height=280,
    )
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# Layout
# ─────────────────────────────────────────────────────────────────────────────

if not metrics_data:
    layout = html.Div([
        html.H2("No Diagnostic Data Found", className="text-danger"),
        html.P("Run Codebase/models/train_all.py to generate model artifacts."),
    ])
else:
    cm_models    = [n for n in ["Random Forest", "2D CNN", "BiLSTM", "Specialist Ensemble"]
                    if n in metrics_data and "confusion_matrix" in metrics_data[n]]
    cm_col_width = max(3, 12 // len(cm_models)) if cm_models else 12

    # ── XAI sample info for subheadings ──────────────────────────────────────
    _top_sample    = (_xai_meta.get("samples") or [{}])[0]
    _top_obj       = _top_sample.get("object", "component")
    _top_ori       = _top_sample.get("orientation", "orientation")
    _top_rf_prob   = _top_sample.get("rf_prob", 0.0)

    layout = html.Div(
        [
            html.Div(
                [
                    html.H1("AI System Diagnostics", className="display-5 fw-bold text-gradient mb-2"),
                    html.P(
                        "Live performance monitoring and explainability for deployed Edge AI models.",
                        className="lead text-secondary",
                    ),
                ],
                className="mb-5 pb-3 border-bottom border-secondary border-opacity-25",
            ),

            # ── Metrics bar charts ────────────────────────────────────────────
            dbc.Row([
                dbc.Col(
                    dbc.Card(dbc.CardBody([dcc.Graph(
                        figure=create_bar_chart(metrics_data, "accuracy", "Model Accuracy", True),
                        config={"displayModeBar": False},
                    )]), className="glass-panel border-0 mb-4"),
                    width=12, md=4,
                ),
                dbc.Col(
                    dbc.Card(dbc.CardBody([dcc.Graph(
                        figure=create_bar_chart(metrics_data, "f1", "System Reliability (F1)", True),
                        config={"displayModeBar": False},
                    )]), className="glass-panel border-0 mb-4"),
                    width=12, md=4,
                ),
                dbc.Col(
                    dbc.Card(dbc.CardBody([dcc.Graph(
                        figure=create_bar_chart(metrics_data, "train_time_sec", "Auto-Calibration Time (s)", False),
                        config={"displayModeBar": False},
                    )]), className="glass-panel border-0 mb-4"),
                    width=12, md=4,
                ),
            ]),

            # ── Deployment recommendation ─────────────────────────────────────
            dbc.Row([
                dbc.Col(create_deployment_recommendation_card(metrics_data), width=12),
            ]),

            # ═══════════════════════════════════════════════════════════════════
            # XAI — EXPLAINABLE AI DIAGNOSTICS
            # Three pillars: Prediction Accuracy · Traceability · Decision Understanding
            # ═══════════════════════════════════════════════════════════════════
            html.Div(
                [
                    html.H2("Explainable AI (XAI) Diagnostics", className="display-6 fw-bold mb-2"),
                    html.P(
                        "Two-pillar framework: Prediction Accuracy (SHAP) · Traceability (Integrated Gradients). "
                        "Every AI prediction is traceable from raw sensor taxel back to the specific feature driving the decision.",
                        className="lead text-secondary",
                    ),
                ],
                className="mt-2 mb-4 pb-3 border-bottom border-secondary border-opacity-25",
            ),

            # ── Pillar 1 & 2 side by side ─────────────────────────────────────
            dbc.Row([

                # Pillar 1 — SHAP Waterfall
                dbc.Col([
                    dbc.Card([
                        dbc.CardBody([
                            dbc.Row([
                                dbc.Col([
                                    dbc.Badge("PILLAR 1 — PREDICTION ACCURACY",
                                              color="info", className="mb-2 px-2 py-1",
                                              style={"fontSize": "0.65rem", "letterSpacing": "0.05em"}),
                                    html.H5("SHAP Feature Contributions", className="fw-bold mb-1"),
                                    html.P(
                                        f"Why did the Random Forest predict "
                                        f"{_top_rf_prob:.0%} slip risk for this {_top_ori} grasp?",
                                        className="text-muted small mb-0",
                                    ),
                                ]),
                            ], className="mb-3 align-items-start"),

                            dcc.Graph(
                                figure=create_shap_waterfall(sample_idx=0),
                                config={"displayModeBar": False},
                            ),

                            html.P(
                                _shap_auto_caption(sample_idx=0) if _xai_loaded
                                else "Run compute_xai.py to enable SHAP explanations.",
                                className="text-muted small mt-2 mb-0",
                                style={"fontStyle": "italic", "lineHeight": "1.6"},
                            ),
                        ])
                    ], className="glass-panel border-0 h-100",
                       style={"borderTop": "3px solid #2563eb"}),
                ], width=12, lg=6, className="mb-4"),

                # Pillar 2 — IG Taxel Attribution Maps
                dbc.Col([
                    dbc.Card([
                        dbc.CardBody([
                            dbc.Row([
                                dbc.Col([
                                    dbc.Badge("PILLAR 2 — TRACEABILITY",
                                              color="warning", className="mb-2 px-2 py-1",
                                              style={"fontSize": "0.65rem", "letterSpacing": "0.05em",
                                                     "color": "#000"}),
                                    html.H5("Integrated Gradients — Sensor Attribution Map", className="fw-bold mb-1"),
                                    html.P(
                                        "CNN neural pathway traced from baseline (no contact) to active sensor state. "
                                        "Red taxels drive the slip prediction; blue taxels are stabilising.",
                                        className="text-muted small mb-0",
                                    ),
                                ]),
                            ], className="mb-3"),

                            dcc.Graph(
                                figure=create_taxel_heatmaps(sample_idx=0),
                                config={"displayModeBar": False},
                            ),

                            html.P(
                                _ig_auto_caption(sample_idx=0) if _xai_loaded
                                else "Run compute_xai.py to enable attribution maps.",
                                className="text-muted small mt-2 mb-0",
                                style={"fontStyle": "italic", "lineHeight": "1.6"},
                            ),
                        ])
                    ], className="glass-panel border-0 h-100",
                       style={"borderTop": "3px solid #ffc107"}),
                ], width=12, lg=6, className="mb-4"),
            ]),

            # ── Confusion matrices ────────────────────────────────────────────
            dbc.Row([
                dbc.Col([
                    dbc.Card([
                        dbc.CardBody([
                            html.H4("What Errors Look Like in Production", className="fw-bold mb-2"),
                            html.P([
                                html.Span("Missed Slip ", className="text-danger fw-bold"),
                                "(false negative) — slip not caught, component dropped.  ",
                                html.Span("False Alarm ", className="text-warning fw-bold"),
                                "(false positive) — unnecessary production stop.",
                            ], className="text-muted small mb-3"),
                            dbc.Row([
                                dbc.Col([
                                    dcc.Graph(
                                        figure=create_confusion_matrix(metrics_data[name], name),
                                        config={"displayModeBar": False},
                                    ),
                                    _make_error_summary(metrics_data[name]),
                                ], width=cm_col_width)
                                for name in cm_models
                            ]),
                        ])
                    ], className="glass-panel border-0"),
                ], width=12, className="mb-4"),
            ]),

            # ── Production Health Monitor (Concept Drift) ─────────────────────
            html.Div(
                [
                    html.H2("Production Health Monitor", className="display-6 fw-bold mb-2"),
                    html.P(
                        "Simulated 30-day confidence distribution tracking — detects when the deployed model "
                        "encounters out-of-distribution components and flags the need for retraining.",
                        className="lead text-secondary",
                    ),
                ],
                className="mt-2 mb-4 pb-3 border-bottom border-secondary border-opacity-25",
            ),

            dbc.Row([
                dbc.Col([
                    dbc.Card([
                        dbc.CardBody([
                            dbc.Row([
                                dbc.Col(
                                    html.H4("Confidence Distribution — Last 30 Days", className="fw-bold mb-0"),
                                    width="auto",
                                ),
                                dbc.Col(
                                    dbc.Badge(_drift_status, color=_drift_color, className="fs-6 px-3 py-2"),
                                    width="auto", className="ms-auto d-flex align-items-center",
                                ),
                            ], className="mb-3 align-items-center"),
                            dcc.Graph(
                                figure=create_drift_chart(_days, _drift_means, _drift_stds),
                                config={"displayModeBar": False},
                            ),
                            html.P(
                                [
                                    html.Strong("Interpretation: "),
                                    "Days 1–20 show stable confidence centred on training distribution. "
                                    "A new component geometry introduced on day 21 causes progressive drift. "
                                    "By day 26 the KL-divergence threshold (0.15) is breached and a retrain flag is raised.",
                                ],
                                className="text-muted small mt-3 mb-0",
                            ),
                        ])
                    ], className="glass-panel border-0 h-100"),
                ], width=12, lg=7, className="mb-4"),

                dbc.Col([
                    dbc.Card([
                        dbc.CardBody([
                            html.H4("Drift Response Protocol", className="fw-bold mb-4"),
                            dbc.ListGroup([
                                dbc.ListGroupItem([html.Strong("Drift Trigger: "), "Confidence KL-divergence > 0.15"],
                                                  className="bg-transparent border-secondary text-dark small py-3"),
                                dbc.ListGroupItem([html.Strong("Response: "), "Automated flag raised to MLOps pipeline"],
                                                  className="bg-transparent border-secondary text-dark small py-3"),
                                dbc.ListGroupItem([html.Strong("Retrain Cadence: "), "Monthly full retrain + weekly incremental update"],
                                                  className="bg-transparent border-secondary text-dark small py-3"),
                                dbc.ListGroupItem([html.Strong("Data Strategy: "), "Flagged session samples added to training set"],
                                                  className="bg-transparent border-secondary text-dark small py-3"),
                                dbc.ListGroupItem([
                                    html.Strong("Downtime: "),
                                    html.Span("Zero", className="text-success fw-bold"),
                                    " — previous model stays live during retrain",
                                ], className="bg-transparent border-secondary text-dark small py-3"),
                            ], flush=True),
                            html.Hr(className="border-secondary opacity-25 my-3"),
                            html.H6("Status Thresholds", className="fw-bold mb-2"),
                            dbc.Row([
                                dbc.Col(dbc.Badge("Stable",           color="success", className="w-100 py-2"), width=4),
                                dbc.Col(dbc.Badge("Drift Warning",    color="warning", className="w-100 py-2"), width=4),
                                dbc.Col(dbc.Badge("Retrain Required", color="danger",  className="w-100 py-2"), width=4),
                            ], className="g-2"),
                            dbc.Row([
                                dbc.Col(html.P("Conf ≥ 0.72", className="text-muted text-center small mt-1 mb-0"), width=4),
                                dbc.Col(html.P("0.62 – 0.72", className="text-muted text-center small mt-1 mb-0"), width=4),
                                dbc.Col(html.P("Conf < 0.62", className="text-muted text-center small mt-1 mb-0"), width=4),
                            ]),
                        ])
                    ], className="glass-panel border-0 h-100"),
                ], width=12, lg=5, className="mb-4"),
            ]),
        ],
        className="animate__animated animate__fadeIn",
    )
